### ISSUE TITLE
有没有办法构建加密的带有“图片处理”参数的下载链接？

### ISSUE THREAD

**Issue by CocaColaCat** [huobazi/carrierwave-qiniu#30]
项目的图片是private的，但同时希望能做处理，不知道如何能构建这样的加密url？

``` code
http://qiniuphotos.qiniudn.com/gogopher.jpg?imageView2/1/w/200/h/200&e=xxxx&token=yyy
```

查看了源码，但还是没有头绪。

@huobazi

**Comment by huobazi** [comment]
和 https://github.com/huobazi/carrierwave-qiniu/issues/15 类似的方法

**Comment by CocaColaCat** [comment]
提供的建议还是没有加密url, 现在的解决方案是构建好 url 后自己加密。

不知道是否有更好的解决方案？

**Comment by huobazi** [comment]
fixed :  https://github.com/huobazi/carrierwave-qiniu/pull/80
