### ISSUE TITLE
生成的图片地址中的斜杠不应转义

### ISSUE THREAD

**Issue by ShiningRay** [huobazi/carrierwave-qiniu#35]
[2] pry(main)> s.icon.url
=> "http://7xivnf.com2.z0.glb.qiniucdn.com/uploads%2Fseries%2Ficon%2F1%2F201242411445734.jpg"

其中路径中的“/”被转义成了“%2F”

**Comment by huobazi** [comment]
这个有影响什么？

**Comment by icyleaf** [comment]
影响视觉美感，而且也浪费字节数。
