### ISSUE TITLE
上传失败截获不到异常

### ISSUE THREAD

**Issue by whlsxl** [huobazi/carrierwave-qiniu#37]

**Comment by huobazi** [comment]
能提供点详细信息么？

**Comment by whlsxl** [comment]
在model save 的时候 如果与服务器连接不通畅 上传失败 没有接获到异常 qiniu这个gem本身也不会抛异常 所以最后没有办法知道上传失败

**Comment by feitian124** [comment]
#39 可能和这个issue有关, 这里异常处理有点问题

**Comment by cpunion** [comment]
最新版本也有这问题，导致上传失败但是记录被保存了，目前只输出了警告。查看了代码：
https://github.com/huobazi/carrierwave-qiniu/blob/master/lib/carrierwave/storage/qiniu.rb#L45

这里并没有处理返回值，应该在这里抛异常。

相关代码：
https://github.com/qiniu/ruby-sdk/blob/1bffe21c5828d1f73241c6b19319b7063a7d17cf/lib/qiniu/upload.rb#L139-L150
https://github.com/qiniu/ruby-sdk/blob/1bffe21c5828d1f73241c6b19319b7063a7d17cf/lib/qiniu/upload.rb#L49-L83
https://github.com/qiniu/ruby-sdk/blob/1bffe21c5828d1f73241c6b19319b7063a7d17cf/lib/qiniu/http.rb#L100-L126

可以看到这里最终返回的是 `return resp_code, resp_body, resp_headers` 但是没有检查处理。

只要配置错误即可重现，只要上传错误都应该异常。
