### ISSUE TITLE
resize_to_fill

### ISSUE THREAD

**Issue by Yohansun** [huobazi/carrierwave-qiniu#43]
对 CarrierWave 本身的裁切图片的
```javascript
version :thumb do
    process :resize_to_fill => [200, 200]
end
```
这个方法 是不是没有用了 也就是您本身并没有集成

**Comment by huobazi** [comment]
应该不会影响到这个功能的，你遇到什么样的问题了？

**Comment by Yohansun** [comment]
如果是CarrierWave 本身的话 写这个方法 本地就会创建 两张图片 一张原图 一张200*200 的图片 但是现在传到七牛上的图片 只有一张原图 avart.url,  200*200的avart.thumb.url 不显示 地址是有的

**Comment by huobazi** [comment]
@Yohansun 
我试了一下，是没有问题的，另外我增加了测试代码，见 https://github.com/huobazi/carrierwave-qiniu/commit/d6752260ad910f745644ac0daf702048aae77556

**Comment by Yohansun** [comment]
好的 谢谢 我看看。

**Comment by Yohansun** [comment]
@huobazi  楼主 我不知道 你有没有看 具体的访问地址 我的正式地址访问是出图片的 但是thumb得访问结果不是图片是这样的
{"error":"Document not found"}

这是测试的地址， 不知道你访问的到吗 url是生成的 但是没有传到7niu 难道是我的配置问题？

**Comment by huobazi** [comment]
@Yohansun  

文件可以传到 qiniu 的，你可以 run 一下 rspec https://github.com/huobazi/carrierwave-qiniu/commit/d6752260ad910f745644ac0daf702048aae77556 

下面是我的结果（3天内删除）：
http://spec-test.qiniudn.com/carrierwave-qiniu-spec/images/478bf71b12.jpg

http://spec-test.qiniudn.com/carrierwave-qiniu-spec/thumb_images/478bf71b12.jpg

**Comment by Yohansun** [comment]
ok , 我再检查下代码 ，辛苦啦 谢谢。
