### ISSUE TITLE
如何添加callbackUrl和persistentNotifyUrl？

### ISSUE THREAD

**Issue by catsky** [huobazi/carrierwave-qiniu#46]
hi 你好
看了一遍代码，好像目前不支持在设置上传策略的时候写入这两个回调参数。请问有办法支持吗？多谢

**Comment by huobazi** [comment]
callback 的场景应该是直传时才有需要吧？比如在 app 内直传成功后通知 server 端。carrierwave-qiniu 是在服务端上传的，结果服务端自然知晓，所以不需要 callback

**Comment by catsky** [comment]
多谢，对于callback你说的没错，但是如果在config里设置了处理命令，如何才能知道处理结束？我看了api文档，好像要借助persistentNotifyUrl，是吗？

**Comment by huobazi** [comment]
我理解你说的意思了，因该和我之前的困惑 https://github.com/qiniu/ruby-sdk/issues/48#issuecomment-21098720 一样，这个 persistentNotifyUrl 因该是 七牛 后来添加的 通知地址。这个场景我认为需要支持，下来需要考虑一下增加这部分支持了，当然，非常欢迎提建议，发 PR 等。

**Comment by huobazi** [comment]
done. https://rubygems.org/gems/carrierwave-qiniu/versions/0.2.1
@catsky 感谢您的贡献！
