### ISSUE TITLE
不支持rails 5？

### ISSUE THREAD

**Issue by kikyous** [huobazi/carrierwave-qiniu#48]
bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'carrierwave-qiniu'. (Bundler::GemRequireError)

**Comment by huobazi** [comment]
rails 5 并没有正式发布，没有针对 rails 5 做过测试。

**Comment by kikyous** [comment]
明天找时间看看

**Comment by kikyous** [comment]
bundle update 了一下就可以用了
