### ISSUE TITLE
gemfile源问题

### ISSUE THREAD

**Issue by qiao2818** [huobazi/carrierwave-qiniu#52]
source 'https://gems.ruby-china.org'

gemfile中直接添加gem 'carrierwave-qiniu'，会安装其他源的carrierwave-qiniu

gem 'carrierwave-qiniu', git: 'https://github.com/huobazi/carrierwave-qiniu.git' 这样才能解决

**Comment by qiao2818** [comment]
这样配置后，进行bundle update

Installing rest-client 1.7.3 (was 1.8.0)

rest-client不是新版本

**Comment by huobazi** [comment]
什么叫 

> 会安装其他源的carrierwave-qiniu
