### ISSUE TITLE
有什么方法能使进度条在七牛上传完成后到达百分百?

### ISSUE THREAD

**Issue by SomeOneToken** [huobazi/carrierwave-qiniu#63]
视频上传的时候要加一个进度条,但是这个进度条在数据存到本地数据库是就走到百分百了,实际上后台还在向七牛上传,并没有完成,这个要怎么解决会好一些?

**Comment by bianjp** [comment]
上传大文件的话最好使用 [Javascript SDK](http://developer.qiniu.com/code/v6/sdk/javascript.html) 在客户端直接上传到七牛吧。这样进度条也好做。

**Comment by SomeOneToken** [comment]
这样啊,主要是这个视频不止要上传到七牛,本地也要保存相应的地址链接,觉得用carrierwave-qiniu会方便些,现在就遇到文件过大上传不了的问题

**Comment by huobazi** [comment]
你的场景使用 https://github.com/huobazi/qiniu_direct_uploader 会更方便些

**Comment by SomeOneToken** [comment]
感谢回复,最后使用jssdk直传
