### ISSUE TITLE
验证失败: Imagecould not download file: execution expired

### ISSUE THREAD

**Issue by Mapana** [huobazi/carrierwave-qiniu#65]
报错信息如题！
`gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'`<br/>
`gem 'carrierwave-qiniu', '~> 0.2.4'`
```ruby
image = Image.new
image.remote_image_url = "http://test.jpg"
image.save!
```
测试时使用remote_image_url的url值是可以访问的

**Comment by huobazi** [comment]
你的服务器和你要下载的图片通信失败
