### ISSUE TITLE
请问这个项目还有在维护吗

### ISSUE THREAD

**Issue by wayne712** [huobazi/carrierwave-qiniu#69]
My problem,
``` 
There was an error while trying to load the gem 'carrierwave-qiniu'. (Bundler::GemRequireError)
Gem Load Error is: You dot't have the 'qiniu-rs' gem installed
```
But qiniu-rs was deprecated.

**Comment by huobazi** [comment]
- 应该算是还在维护吧，你可以看到2016年10月17日还有 commit 还在做版本更新。
- 运行 ``` bundle show carrierwave-qiniu``` 看看贴内容上来。

**Comment by cqpx** [comment]
我也是遇到这个问题，Gemfile里直接写`gem 'carrierwave-qiniu'`后自动安装的0.0.7.1。必须写成`gem 'carrierwave-qiniu', '~> 0.2.6'`
