### ISSUE TITLE
在做头像上传功能的时候，已经上传的图片没法覆盖

### ISSUE THREAD

**Issue by gaoguoxin** [huobazi/carrierwave-qiniu#7]
大致流程是这样，用户在第一次上传了一头像图片后，觉得不合适，又重新选择了一张想进行覆盖，结果会报错：

``` ruby
Uploading Failed. HTTP Status Code: 614. HTTP response body: :error => file exists.
```

根据七牛的api，应该是在上传策略里面将scope的值赋值为<bucket>:<key>的形式，发现在这个gem里面没法进行自定义上传/下载/管理 策略。或者说我没有找到正确的方法？

**Comment by Gaolz** [comment]
@huobazi 
版本：0.2.1 
在 config/initializers/carrierwave.rb 中设置了
`config.qiniu_can_overwrite = true
 `
依然不能覆盖原来的图片。
