### ISSUE TITLE
store和copy等不应该raise exception

### ISSUE THREAD

**Issue by undeflife** [huobazi/carrierwave-qiniu#74]
以Carrierwave的风格,要raise也是在store!里raise

**Comment by FrankFang** [comment]
请问要怎么改？
有时间来个 PR 吗？

**Comment by undeflife** [comment]
我提issues的时候没描述清楚,主要是个观念问题.在文件上传时,如果文件存在,七牛会返回614，现有的代码会raise Exception. 我觉得这个响应结果不应该raise.

**Comment by huobazi** [comment]
在这里抛出异常当时是考虑了便于调试和及时发现错误，毕竟七牛中间隔了一层，为了及早发现非正常响应。
