### ISSUE TITLE
上传的文件莫名被删除

### ISSUE THREAD

**Issue by insub** [huobazi/carrierwave-qiniu#82]
我使用了 carrierwave-qiniu 来做上传的一些工作，最近经常发现会有上传完毕的图片在过了几天之后莫名地被删除了。
我请七牛那边大概查了一下，发出的请求头里有 carrierwave 的字样
问题是，我们的项目根本没有删除图片的功能，也从来没用到七牛的删除接口

所以想请问一下，carrierwave-qiniu 在那些情况下，会向七牛的服务器发送删除资源的请求？

**Comment by huobazi** [comment]
@insub 你是否使用了 ``` qiniu_delete_after_days ``` 这个参数？
